version: "3.7"

services:
  gundns:
    image: lumeweb/gundns:master
    container_name: gundns
    restart: unless-stopped
    environment:
      - RPC_PROXY_HOST=rpcproxy
      - RPC_PROXY_PORT=80
    volumes:
      - /opt/dnsrelay/data/gundns:/app/data
    expose:
      - 80
  rpcproxy:
    image: lumeweb/rpcproxy:develop
    container_name: rpcproxy
    restart: always
    env_file:
      - /opt/dnsrelay/data/.env
    volumes:
      - /opt/dnsrelay/data/gundns:/app/data
      - /opt/dnsrelay/data:/data
    expose:
      - 80
  handshake:
    image: skynetlabs/hsd:3.0.1
    command: --chain-migrate=2 --spv
    container_name: handshake
    environment:
      - HSD_LOG_CONSOLE=false
      - HSD_HTTP_HOST=0.0.0.0
      - HSD_NETWORK=main
      - HSD_PORT=12037
    expose:
      - 12037
    ports:
      - 12037
  certbot:
    image: certbot/certbot:latest
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    container_name: certbot
    restart: unless-stopped
    volumes:
      - /opt/dnsrelay/data/certbot:/etc/letsencrypt
      - /opt/dnsrelay/data/certbot/www:/var/www/certbot
  dashboard:
    image:  lumeweb/dns-relay-dashboard:develop
    expose:
      - 80
    volumes:
      - /opt/dnsrelay/data:/data
      - /opt/dnsrelay/data/certbot:/etc/letsencrypt
      - /opt/dnsrelay/data/certbot/www:/var/www/certbot
  nginx:
    image: lumeweb/dns-relay-nginx:develop
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /opt/dnsrelay/data/certbot:/etc/letsencrypt
      - /opt/dnsrelay/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gundns
      - rpcproxy
      - dashboard
      - nginx_ssl_init
  nginx_ssl_init:
    image: emberstack/openssl
    volumes:
      - /opt/dnsrelay/data/certbot:/etc/letsencrypt
    command: sh -c "mkdir -p /etc/letsencrypt/live/dnsrelay && test ! -f /etc/letsencrypt/live/dnsrelay/fullchain.pem && /usr/bin/openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj '/CN=dns-relay-certificate' -keyout /etc/letsencrypt/live/dnsrelay/privkey.pem  -out /etc/letsencrypt/live/dnsrelay/fullchain.pem && cp /etc/letsencrypt/live/dnsrelay/fullchain.pem /etc/letsencrypt/live/dnsrelay/chain.pem"
    restart: "no"
    depends_on:
      - certbot
